---
owner: iamimmanuelraj
repo: uptime.immanuelraj.dev
user-agent: uptime-immanuelraj-dev
sites:
  - name: Portfolio
    url: https://immanuelraj.dev
    icon: https://immanuelraj.dev/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
    slug: portfolio
    type: globalping
    location: World
    ipv6: true
  - name: Status Page
    url: https://status.immanuelraj.dev
    icon: https://status.immanuelraj.dev/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
    slug: status-page
    type: globalping
    location: World
    ipv6: true
status-website:
  cname: uptime.immanuelraj.dev
  logoUrl: https://immanuelraj.dev/favicon.ico
  name: Immanuel's Status
  introTitle: "**Immanuel's** service status &amp; uptime monitor."
  introMessage: "Hi, I'm Immanuel — I care about keeping my services reliable and transparent.
    This page gives you a live look at the health of everything I run. If something's down,
    I already know about it and I'm on it. Visit [immanuelraj.dev](https://immanuelraj.dev) to learn more about me."
  navbar:
    - title: Website
      href: https://immanuelraj.dev