---
owner: iamimmanuelraj
repo: uptime.immanuelraj.dev
user-agent: uptime-immanuelraj-dev
sites:
  - name: Portfolio
    url: https://immanuelraj.dev
    icon: https://immanuelraj.dev/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
    slug: portfolio
    type: globalping
    location: World
    ipv6: true
  - name: Status Page
    url: https://status.immanuelraj.dev
    icon: https://status.immanuelraj.dev/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
    slug: portfolio
    type: globalping
    location: World
    ipv6: true
delay: 0
assignees:
  - iamimmanuelraj
skipDeleteIssues: false
skipDescriptionUpdate: false
skipTopicsUpdate: false
skipHomepageUpdate: false
workflowSchedule:
  uptime: "*/5 * * * *"
  graphs: 0 0 * * *
  responseTime: 0 23 * * *
  summary: 0 0 * * *
  updateTemplate: 0 0 * * *
commitMessages:
  statusChange: ":$EMOJI: $URL is $STATUS ($RESPONSE_TIME in $RESPONSE_TIME ms)
    [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci]"
  responseTime: ":pencil: Update response time [skip ci]"
  staticSite: ":pencil: Update static site [skip ci]"
  summary: ":card_file_box: Update status summary [skip ci] [upptime]"
  readmeUpdateMessage: ":pencil: Update summary in README [skip ci] [upptime]"
i18n:
  lang: en
status-website:
  cname: uptime.immanuelraj.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Up Time Check
  introTitle: "**Upptime** is the open-source uptime monitor and status page,
    powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from
    our [GitHub repository](https://github.com/upptime/upptime). No server
    required — just GitHub Actions, Issues, and Pages. [**Get your own for
    free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
