---
owner: iamimmanuelraj
repo: uptime.immanuelraj.dev
user-agent: uptime-immanuelraj-dev
sites:
  - name: Portfolio
    url: https://immanuelraj.dev
    icon: https://immanuelraj.dev/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
    slug: portfolio
    type: globalping
    location: World
    ipv6: true
  - name: Status Page
    url: https://status.immanuelraj.dev
    icon: https://status.immanuelraj.dev/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
    slug: status-page
    type: globalping
    location: World
    ipv6: true
status-website:
  cname: uptime.immanuelraj.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Immanuel's Status
  introTitle: "**Immanuel's** service status &amp; uptime monitor."
  introMessage: Real-time availability tracking for all services at [immanuelraj.dev](https://immanuelraj.dev).
    Powered entirely by GitHub Actions — no external servers. Check the [history](https://github.com/$OWNER/$REPO/issues)
    for past incidents and response times.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO